### PR TITLE
Added UV offset support for checker texture

### PR DESCRIPTION
**Pull request by fewo**

### CODE REVIEW

**Comment by tunabrain** [comment]
Interesting. I can see the merit of adding a texture offset, but I'm not sure why the default is 0.5 (i.e. top left is now actually the center of the texture). I'm also not sure how this interacts with sampling.

**Comment by fewo** [comment]
You right I put 0.5 just for testing forgot to reset the value to 0. Not sure either about the sampling, what method are you using right now  ?

**Comment by tunabrain** [comment]
I think the easiest solution for now is to fall back to uniform sampling when the offset is non-zero. Basically, remove the modifications in `CheckerTexture::pdf` and instead add the following:

* A `return 1.0f;` at the top of `CheckerTexture::pdf` if any offset is non-zero
* A `return uv;` at the top of `CheckerTexture::sample` if any offset is non-zero

If you can change the above, set the default offset to 0 and remove the changes in the materialtest, this is ready to be merged.

There is also a user-friendliness question here (which I'm not sure how to answer), which is whether the offset should be in terms of UV-coordinates or in terms of squares. Currently it's the latter, i.e. an offset of 0.5, 0.5 scrolls by half a square. On its own I think this is fine, but in the future I'd like to switch to a general UV transform feature that works for all textures, in which case the former is preferrable (i.e. an offset of 0.5, 0.5 scrolls by half the texture).

**Comment by fewo** [comment]
Ok I will do the changes. I will think about the general UV transform feature

**Comment by tunabrain** [comment]
Closed due to inactivity - let me know if you want me to reopen.

**Pull request closed without merging**
